name: Code Analysis with CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze Code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/setup-codeql@latest  # Zmieniono na najnowszą wersję

      - name: Initialize CodeQL database
        run: codeql database init --language=javascript  # Zmieniaj w zależności od języka

      - name: Perform CodeQL analysis
        run: codeql analyze --threads 2

      - name: Upload CodeQL results
        uses: github/codeql-action/upload-results@latest
