name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]  # Możesz zmienić na dowolną wersję Node.js

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set up .env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
        export $(cat .env | xargs)
        echo "BOT_TOKEN is set to: $BOT_TOKEN"  # Debugging line
    - run: npm install
    - name: Run bot in background
      run: |
        npm run start &  # Uruchomienie bota w tle
        sleep 10  # Czekaj 10 sekund na uruchomienie bota
        # Sprawdzamy, czy pojawiły się błędy w logach (sprawdzamy plik bot.log), ignorując błędy specyficzne dla Lavalinka
        if grep -q -e "Unhandled promise rejection" -e "error" -e "Exception" -e "fatal" bot.log && ! grep -q "Uncaught exception: Unhandled error. LavalinkNode" bot.log; then
          echo "Test niepowodzenia: Wystąpił poważny błąd w logach!"
          exit 1
        else
          echo "Test zakończony sukcesem: Bot działa bez krytycznych błędów."
          exit 0  # Zakończenie z sukcesem, jeśli nie znaleziono błędów
        fi
