name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Używamy tylko jednej wersji Node.js
    strategy:
      matrix:
        node-version: [22.x]  # Możesz zmienić na dowolną wersję Node.js, którą chcesz testować
        # Jeśli chcesz zmienić wersję, po prostu zmień na np. [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set up .env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
        export $(cat .env | xargs)
        echo "BOT_TOKEN is set to: $BOT_TOKEN"  # Debugging line
    - run: npm install
    - run: npm run start
    - name: Wait for 10 seconds and check logs
      run: |
        sleep 10  # Czekaj 10 sekund na uruchomienie bota
        # Sprawdzamy, czy pojawił się jakiś błąd
        if grep -q -e "Unhandled promise rejection" -e "error" -e "Exception" -e "fatal" logs.txt; then
          echo "Test niepowodzenia: Wystąpił poważny błąd w logach!"
          exit 1
        else
          echo "Test zakończony sukcesem: Bot działa bez krytycznych błędów."
          exit 0  # Jeśli nie znaleziono błędów, zakończ z sukcesem
        fi
